"""dex-retargeting library wrapper for retarget_dev pipeline.

Wraps SeqRetargeting from the dex-retargeting library to implement
our RetargetingModel ABC. Supports vector/position/DexPilot modes
via YAML config files.

Usage:
    model = DexRetargetModel.from_config("config/dg5f_right_vector.yml")
    q = model.retarget(hand_keypoints)
"""

import logging
import time
from pathlib import Path
from typing import Optional

import numpy as np

from retarget_dev.models.base import RetargetingModel
from retarget_dev.sensing.common import HandKeypoints

logger = logging.getLogger(__name__)


class DexRetargetModel(RetargetingModel):
    """Wrapper around dex-retargeting's SeqRetargeting.

    Converts HandKeypoints (21, 3) → ref_value format expected by
    the underlying optimizer (vector / dexpilot / position) using the
    canonical `target_link_human_indices` stored on the optimizer.
    """

    def __init__(self, config_path: str):
        from dex_retargeting.retargeting_config import RetargetingConfig

        self._config_path = config_path
        config = RetargetingConfig.load_from_file(config_path)
        self._retargeting = config.build()

        # Single source of truth: the optimizer's own indices.
        # - vector:   (2, N) array from YAML target_link_human_indices
        # - dexpilot: (2, num_pairs + num_fingers) array auto-generated by
        #             DexPilotOptimizer.__init__ via generate_link_indices()
        # - position: (N,) array of fingertip indices
        # This matches detect_dg5f.py's pattern, which is the only ref_value
        # builder verified to work for all optimizer types.
        optimizer = self._retargeting.optimizer
        self._retargeting_type = optimizer.retargeting_type
        self._human_indices = optimizer.target_link_human_indices

        self._last_solve_ms = 0.0

        logger.info(
            "DexRetargetModel loaded (type=%s, config=%s, joints=%d)",
            self._retargeting_type, Path(config_path).name,
            len(self._retargeting.joint_names),
        )

    @classmethod
    def from_config(cls, config_path: str) -> "DexRetargetModel":
        return cls(config_path)

    def retarget(self, keypoints: HandKeypoints) -> np.ndarray:
        """Convert HandKeypoints → robot joint angles."""
        kp = keypoints.keypoints_3d  # (21, 3)
        ref_value = self._build_ref_value(kp)

        t0 = time.perf_counter()
        q = self._retargeting.retarget(ref_value)
        self._last_solve_ms = (time.perf_counter() - t0) * 1000

        return q

    def get_joint_names(self) -> list[str]:
        return list(self._retargeting.joint_names)

    def get_debug_info(self, keypoints: HandKeypoints, q: np.ndarray) -> Optional[dict]:
        return {
            "solve_time_ms": self._last_solve_ms,
            "type": self._retargeting_type,
            "dg5f_angles_deg": np.degrees(q),
        }

    @property
    def solve_time_ms(self) -> float:
        return self._last_solve_ms

    def _build_ref_value(self, kp: np.ndarray) -> np.ndarray:
        """Convert (21, 3) keypoints to optimizer-specific input.

        Mirrors detect_dg5f.py:70-78 — uses the optimizer's stored
        target_link_human_indices so vector and dexpilot share the
        exact same code path the library expects.
        """
        indices = self._human_indices
        if self._retargeting_type == "POSITION":
            return kp[indices, :]
        origin_indices = indices[0, :]
        task_indices = indices[1, :]
        return kp[task_indices, :] - kp[origin_indices, :]
